<?php 

class MY_Form_validation extends CI_Form_validation
{

    private $required = array();

 	function __construct($rules = array())
    {
        parent::__construct($rules);
    }
    
    function get_error_message() 
    {
    	return $this->error_string;
    }
    
    function get_error_messages() 
    {
    	return $this->_error_array;
    }

    function set_rules($field, $label = '', $rules = array(), $errors = array())
    {
        if (strstr($rules, 'required'))
        {
            $this->required[] = $field;
        }
        return parent::set_rules($field, $label, $rules, $errors); // TODO: Change the autogenerated stub
    }

    public function is_required($field)
    {
        return in_array($field, $this->required);
    }
	
}

?>